const pages=[
    {
        name:"Project",
        entries:[
            {
                name:"Description",
                link:"https://2021.igem.org/Team:Uppsala/Description"
            },
            {
                name:"Proof of Concept",
                link:"https://2021.igem.org/Team:Uppsala/Proof_Of_Concept"
            },
            {
                name:"Engineering<br>Success",
                link:"https://2021.igem.org/Team:Uppsala/Engineering"
            },
            {
                name:"Contribution",
                link:"https://2021.igem.org/Team:Uppsala/Contribution"
            },
            {
                name:"Software tool",
                link:"https://2021.igem.org/Team:Uppsala/Software"
            },
        ]
    },
    {
        name:"Experiments",
        entries:[
            {
                name:"Results",
                link:"https://2021.igem.org/Team:Uppsala/Results"
            },
            {
                name:"Modelling",
                link:"https://2021.igem.org/Team:Uppsala/Model"
            },
            {
                name:"Protocols",
                link:"https://2021.igem.org/Team:Uppsala/Experiments"
            },
            {
                name:"Notebook",
                link:"https://2021.igem.org/Team:Uppsala/Notebook"
            },
            {
                name:"Parts tool",
                link:"https://2021.igem.org/Team:Uppsala/Parts"
            },
            {
                name:"Safety",
                link:"https://2021.igem.org/Team:Uppsala/Safety"
            },
        ]
    },
    {
        name:"Human Practice",
        entries:[
            {
                name:"Overview",
                link:"https://2021.igem.org/Team:Uppsala/Human_Practices"
            },
            {
                name:"Integrated<br>Human Practice",
                link:"https://2021.igem.org/Team:Uppsala/Human_Practices"
            },
            {
                name:"Proposed<br>Implementation",
                link:"https://2021.igem.org/Team:Uppsala/Implementation"
            },
            {
                name:"Education &<br>Communication",
                link:"https://2021.igem.org/Team:Uppsala/Communication"
            },
            {
                name:"Inclusivity",
                link:"https://2021.igem.org/Team:Uppsala/Inclusivity"
            },
            {
                name:"Sustainable<br>Development",
                link:"https://2021.igem.org/Team:Uppsala/Sustainable"
            },
        ]
    },
    {
        name:"People",
        entries:[
            {
                name:"Team",
                link:"https://2021.igem.org/Team:Uppsala/Team"
            },
            {
                name:"Collaboration",
                link:"https://2021.igem.org/Team:Uppsala/Collaborations"
            },
            {
                name:"Attribution",
                link:"https://2021.igem.org/Team:Uppsala/Attributions"
            },
            {
                name:"Sponsors",
                link:"https://2021.igem.org/Team:Uppsala/Sponsors"
            },
        ]
    },
    {
        name:"Videos",
        entries:[
            {
                name:"Final<br>Presentation",
                link:"https://2021.igem.org/Team:Uppsala/Description"
            },
            {
                name:"Promotional<br>Video",
                link:"https://www.youtube.com/watch?v=avKlAK5-1ks"
            },
            {
                name:"Molecular<br>Dynamics",
                link:"https://2021.igem.org/Team:Uppsala/Model"
            },
        ]
    },
    {
        name:"Judging",
        entries:[
            {
                name:"Judging Form",
                link:"https://2021.igem.org/Team:Uppsala"
            },
            {
                name:"Awards",
                link:"https://2021.igem.org/Team:Uppsala"
            },
        ]
    },
]